# Generated by Django 4.2.4 on 2023-08-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(max_length=50)),
                ('tuesday', models.CharField(max_length=50)),
                ('wednesday', models.CharField(max_length=50)),
                ('thursday', models.CharField(max_length=50)),
                ('friday', models.CharField(max_length=50)),
                ('saturday', models.CharField(max_length=50)),
                ('sunday', models.CharField(max_length=50)),
            ],
        ),
    ]
