# Generated by Django 4.2.4 on 2023-08-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_alter_dashboard_sunday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='friday',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='monday',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='saturday',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='thursday',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='tuesday',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='wednesday',
            field=models.DateTimeField(),
        ),
    ]
