# Generated by Django 4.2.4 on 2023-08-17 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_alter_dashboard_friday_alter_dashboard_monday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='friday',
            new_name='Friday',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='monday',
            new_name='Monday',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='saturday',
            new_name='Saturday',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='sunday',
            new_name='Sunday',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='thursday',
            new_name='Thursday',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='tuesday',
            new_name='Tuesday',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='wednesday',
            new_name='Wednesday',
        ),
    ]
