# Generated by Django 4.2.4 on 2023-08-25 11:23

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_rename_friday_dashboard_friday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('explanation', models.TextField()),
                ('content', tinymce.models.HTMLField()),
                ('saved', models.DateTimeField()),
            ],
        ),
    ]
