# Generated by Django 4.2.4 on 2023-08-25 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0007_notes_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='saved',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
    ]
