# Generated by Django 4.2.4 on 2023-08-28 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0009_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='upload_time',
        ),
    ]
