# Generated by Django 4.2.4 on 2023-09-20 16:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspace', '0019_recentworks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='added_on',
        ),
        migrations.CreateModel(
            name='Deadlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(null=True)),
                ('ended_on', models.DateField(default=datetime.date(2023, 9, 20))),
                ('author', models.ForeignKey(default='anonymous', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
