# Generated by Django 4.2.7 on 2023-11-07 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0021_storage_folder_alter_deadlines_ended_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadlines',
            name='ended_on',
            field=models.DateField(default=datetime.date(2023, 11, 7)),
        ),
    ]
