# Generated by Django 4.2.7 on 2024-03-19 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0023_alter_deadlines_ended_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadlines',
            name='ended_on',
            field=models.DateField(default=datetime.date(2024, 3, 20)),
        ),
    ]
